spring:
  application:
    name: course-management
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:courseapp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  error:
    include-stacktrace: ALWAYS
app:
  plugin:
    url: